name = "workers-kv-from-rust"
type = "rust"
account_id = ""
workers_dev = true
compatibility_date = "2022-01-16"
route = ""
zone_id = ""

kv_namespaces = [ 
         { binding = "KV_FROM_RUST", id = "0e9c89d835a04fde8e7ab23159421da5", preview_id = "9afc93a8caa747258843dc6b9fe6fd3c" }
]

